name: CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - 'docs.json'
      - '**/*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'docs/**'
      - 'docs.json'
      - '**/*.md'

jobs:
  test-example-plugin:
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build runner-package
        run: |
          cd runner-package
          npm install
          npm run build
      - uses: drownek/plugwright-action@v1
        with:
          java-version: "17"
          node-version: "24"
          working-directory: "./example_plugin"
