name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-example-plugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: drownek/paperwright-action@v1
